title: Muhammad Faizan
logo: /assets/Faizans_photo.jpg
description: "A personal site featuring research highlights, programming, and occasional thoughts on life"
show_downloads: true
theme: jekyll-theme-minimal
